services:
  audio-analysis-backend:
    build: ./backend
    platform: linux/amd64
    container_name: audio-analysis-backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - ./data:/data
    environment:
      - PYTHONUNBUFFERED=1

  audio-analysis-frontend:
    build: ./frontend
    container_name: audio-analysis-frontend
    ports:
      - "3000:80"
    depends_on:
      - audio-analysis-backend