services:
  audio-analysis-backend:
    image: ghcr.io/binuengoor/audio-analysis-key-bpm-backend:latest
    container_name: audio-analysis-backend
    platform: linux/amd64
    restart: unless-stopped 
    ports:
      - "8000:8000"
    volumes:
      - ./data:/data
    environment:
      - PYTHONUNBUFFERED=1

  audio-analysis-frontend:
    image: ghcr.io/binuengoor/audio-analysis-key-bpm-frontend:latest
    container_name: audio-analysis-frontend
    platform: linux/amd64
    restart: unless-stopped 
    ports:
      - "3000:80"
    depends_on:
      - audio-analysis-backend
